
const lightCodeTheme = require('prism-react-renderer/themes/github');
const darkCodeTheme = require('prism-react-renderer/themes/dracula');

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'Sunny Ravindra Bharne',
  tagline: 'Devops approach for Automation Test Engirneers',
  favicon: 'img/Logo.svg',
  url: 'https://botcat.org',
  baseUrl: '/',
  organizationName: 'Sunny Ravindra', // Usually your GitHub org/user name.
  projectName: 'Sunny Ravindra', // Usually your repo name.
  onBrokenLinks: 'throw',
  onBrokenMarkdownLinks: 'warn',
  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },
  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          sidebarPath: require.resolve('./sidebars.js'),
          routeBasePath: '/',
        },
        blog: {
          showReadingTime: true,
          editUrl:
            'https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/',
        },
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      }),

    ],
  ],
  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      image: 'img/docusaurus-social-card.jpg',
      colorMode: {
        defaultMode: 'light',
        disableSwitch: true,
        respectPrefersColorScheme: false,
      },
      docs: {
        sidebar: {
          hideable: true,
          autoCollapseCategories: true,
        },
      },
      navbar: {
        title: 'Sunny Ravindra Bharne',
        hideOnScroll: true,
        logo: {
          alt: 'QAOPS Logo',
          src: 'img/Logo.svg',
        },
        items: [
          {
            type: 'docSidebar',
            sidebarId: 'myAutogeneratedSidebar',
            position: 'left',
            label: 'Skills',
          },
          // {to: '/blog', label: 'Blog', position: 'left'},
          { to: '/docs/ContactMe', label: 'Contact Me', position: 'right' },
          {
            type: 'html',
            position: 'right',
            value: '<a href="/resume/SunnyRavindra_Resume.pdf" download>Resume</a>',
          },
          { to: 'https://www.linkedin.com/in/sunnybharne/', label: 'LinkedIn', position: 'right' },
          { to: 'https://github.com/sunnyRavindra', label: 'Github', position: 'right' },
          { to: 'https://www.linkedin.com/in/sunnybharne/details/certifications/', label: 'Certifications', position: 'right' },
        ],
      },
      footer: {
        style: 'light',
        copyright: `Sunny Ravindra Bharne`,
      },
      prism: {
        theme: lightCodeTheme,
        darkTheme: darkCodeTheme,
      },
    }),
};

module.exports = config;
