const sidebars = {
  myAutogeneratedSidebar: [
    'AboutMe',
    {
      type: 'category',
      label: 'Test Automation',
      collapsed: false,
      items: [
        'TestAutomation/Selenium',
        'TestAutomation/RestAssured',
        'TestAutomation/RobotFramework',
        'TestAutomation/PlayWright',
        'TestAutomation/Appium',
        'TestAutomation/SoapUI',
      ],
    },
    {
      type: 'category',
      label: 'Automation Framework',
      collapsed: false,
      items: [
        'AutomationFramework/AutomationFramework',
        'AutomationFramework/TestNg',
        'AutomationFramework/Cucumber',
        'AutomationFramework/Grid',
        'AutomationFramework/Maven',
        'AutomationFramework/Log4J',
      ],
    },
    {
      type: 'category',
      label: 'Programing Language',
      collapsed: false,
      items: [
        'ProgramingLanguage/Java',
        'ProgramingLanguage/Python',
        'ProgramingLanguage/Javascript',
        'ProgramingLanguage/TypeScript',
        'ProgramingLanguage/DSA',
      ],
    },
    {
      type: 'category',
      label: 'DevOps',
      collapsed: false,
      items: [
        'Devops/Docker',
      ],
    },
    {
      type: 'category',
      label: 'Test Management',
      collapsed: false,
      items: [
        'TestManagement/Jira',
        'TestManagement/Xray',
        'TestManagement/Zephyr',
      ],
    },
  ],
}

module.exports = sidebars;
