import React from 'react';
import ComponentCreator from '@docusaurus/ComponentCreator';

export default [
  {
    path: '/__docusaurus/debug',
    component: ComponentCreator('/__docusaurus/debug', 'f97'),
    exact: true
  },
  {
    path: '/__docusaurus/debug/config',
    component: ComponentCreator('/__docusaurus/debug/config', 'c5a'),
    exact: true
  },
  {
    path: '/__docusaurus/debug/content',
    component: ComponentCreator('/__docusaurus/debug/content', '997'),
    exact: true
  },
  {
    path: '/__docusaurus/debug/globalData',
    component: ComponentCreator('/__docusaurus/debug/globalData', '74f'),
    exact: true
  },
  {
    path: '/__docusaurus/debug/metadata',
    component: ComponentCreator('/__docusaurus/debug/metadata', '3b0'),
    exact: true
  },
  {
    path: '/__docusaurus/debug/registry',
    component: ComponentCreator('/__docusaurus/debug/registry', '656'),
    exact: true
  },
  {
    path: '/__docusaurus/debug/routes',
    component: ComponentCreator('/__docusaurus/debug/routes', '690'),
    exact: true
  },
  {
    path: '/blog',
    component: ComponentCreator('/blog', '9a3'),
    exact: true
  },
  {
    path: '/blog/2021/08/26/welcome',
    component: ComponentCreator('/blog/2021/08/26/welcome', 'ffa'),
    exact: true
  },
  {
    path: '/blog/archive',
    component: ComponentCreator('/blog/archive', '419'),
    exact: true
  },
  {
    path: '/blog/first-blog-post',
    component: ComponentCreator('/blog/first-blog-post', 'a94'),
    exact: true
  },
  {
    path: '/blog/long-blog-post',
    component: ComponentCreator('/blog/long-blog-post', 'ae7'),
    exact: true
  },
  {
    path: '/blog/mdx-blog-post',
    component: ComponentCreator('/blog/mdx-blog-post', '06d'),
    exact: true
  },
  {
    path: '/blog/tags',
    component: ComponentCreator('/blog/tags', 'de9'),
    exact: true
  },
  {
    path: '/blog/tags/docusaurus',
    component: ComponentCreator('/blog/tags/docusaurus', '4cf'),
    exact: true
  },
  {
    path: '/blog/tags/hello',
    component: ComponentCreator('/blog/tags/hello', 'f6d'),
    exact: true
  },
  {
    path: '/blog/tags/hola',
    component: ComponentCreator('/blog/tags/hola', 'e62'),
    exact: true
  },
  {
    path: '/',
    component: ComponentCreator('/', 'ed7'),
    routes: [
      {
        path: '/',
        component: ComponentCreator('/', 'a8d'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/AutomationFramework/',
        component: ComponentCreator('/AutomationFramework/', '5aa'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/AutomationFramework/Cucumber',
        component: ComponentCreator('/AutomationFramework/Cucumber', 'dcc'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/AutomationFramework/Grid',
        component: ComponentCreator('/AutomationFramework/Grid', 'acb'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/AutomationFramework/Log4J',
        component: ComponentCreator('/AutomationFramework/Log4J', '0f7'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/AutomationFramework/Maven',
        component: ComponentCreator('/AutomationFramework/Maven', '4d0'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/AutomationFramework/TestNg',
        component: ComponentCreator('/AutomationFramework/TestNg', 'd24'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Devops/Docker',
        component: ComponentCreator('/Devops/Docker', '33f'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/ProgramingLanguage/DSA',
        component: ComponentCreator('/ProgramingLanguage/DSA', '43f'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/ProgramingLanguage/Java',
        component: ComponentCreator('/ProgramingLanguage/Java', '3ad'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/ProgramingLanguage/Javascript',
        component: ComponentCreator('/ProgramingLanguage/Javascript', '228'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/ProgramingLanguage/Python',
        component: ComponentCreator('/ProgramingLanguage/Python', '566'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/ProgramingLanguage/TypeScript',
        component: ComponentCreator('/ProgramingLanguage/TypeScript', '9c8'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/TestAutomation/Appium',
        component: ComponentCreator('/TestAutomation/Appium', '54c'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/TestAutomation/PlayWright',
        component: ComponentCreator('/TestAutomation/PlayWright', 'bf4'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/TestAutomation/RestAssured',
        component: ComponentCreator('/TestAutomation/RestAssured', 'fdb'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/TestAutomation/RobotFramework',
        component: ComponentCreator('/TestAutomation/RobotFramework', '4d1'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/TestAutomation/Selenium',
        component: ComponentCreator('/TestAutomation/Selenium', 'f45'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/TestAutomation/SoapUI',
        component: ComponentCreator('/TestAutomation/SoapUI', 'edd'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/TestingConcepts/Testing',
        component: ComponentCreator('/TestingConcepts/Testing', 'deb'),
        exact: true
      },
      {
        path: '/TestManagement/Jira',
        component: ComponentCreator('/TestManagement/Jira', '3ca'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/TestManagement/Xray',
        component: ComponentCreator('/TestManagement/Xray', 'bc9'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/TestManagement/Zephyr',
        component: ComponentCreator('/TestManagement/Zephyr', 'c6b'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      }
    ]
  },
  {
    path: '*',
    component: ComponentCreator('*'),
  },
];
