import React from 'react';
import ComponentCreator from '@docusaurus/ComponentCreator';

export default [
  {
    path: '/__docusaurus/debug',
    component: ComponentCreator('/__docusaurus/debug', 'f97'),
    exact: true
  },
  {
    path: '/__docusaurus/debug/config',
    component: ComponentCreator('/__docusaurus/debug/config', 'c5a'),
    exact: true
  },
  {
    path: '/__docusaurus/debug/content',
    component: ComponentCreator('/__docusaurus/debug/content', '997'),
    exact: true
  },
  {
    path: '/__docusaurus/debug/globalData',
    component: ComponentCreator('/__docusaurus/debug/globalData', '74f'),
    exact: true
  },
  {
    path: '/__docusaurus/debug/metadata',
    component: ComponentCreator('/__docusaurus/debug/metadata', '3b0'),
    exact: true
  },
  {
    path: '/__docusaurus/debug/registry',
    component: ComponentCreator('/__docusaurus/debug/registry', '656'),
    exact: true
  },
  {
    path: '/__docusaurus/debug/routes',
    component: ComponentCreator('/__docusaurus/debug/routes', '690'),
    exact: true
  },
  {
    path: '/blog',
    component: ComponentCreator('/blog', '9a3'),
    exact: true
  },
  {
    path: '/blog/2021/08/26/welcome',
    component: ComponentCreator('/blog/2021/08/26/welcome', 'ffa'),
    exact: true
  },
  {
    path: '/blog/archive',
    component: ComponentCreator('/blog/archive', '419'),
    exact: true
  },
  {
    path: '/blog/first-blog-post',
    component: ComponentCreator('/blog/first-blog-post', 'a94'),
    exact: true
  },
  {
    path: '/blog/long-blog-post',
    component: ComponentCreator('/blog/long-blog-post', 'ae7'),
    exact: true
  },
  {
    path: '/blog/mdx-blog-post',
    component: ComponentCreator('/blog/mdx-blog-post', '06d'),
    exact: true
  },
  {
    path: '/blog/tags',
    component: ComponentCreator('/blog/tags', 'de9'),
    exact: true
  },
  {
    path: '/blog/tags/docusaurus',
    component: ComponentCreator('/blog/tags/docusaurus', '4cf'),
    exact: true
  },
  {
    path: '/blog/tags/hello',
    component: ComponentCreator('/blog/tags/hello', 'f6d'),
    exact: true
  },
  {
    path: '/blog/tags/hola',
    component: ComponentCreator('/blog/tags/hola', 'e62'),
    exact: true
  },
  {
    path: '/tags',
    component: ComponentCreator('/tags', 'e49'),
    exact: true
  },
  {
    path: '/tags/excalidraw',
    component: ComponentCreator('/tags/excalidraw', 'faa'),
    exact: true
  },
  {
    path: '/',
    component: ComponentCreator('/', '759'),
    exact: true
  },
  {
    path: '/',
    component: ComponentCreator('/', 'f9d'),
    routes: [
      {
        path: '/1Selenium',
        component: ComponentCreator('/1Selenium', '1c9'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/1TestNg',
        component: ComponentCreator('/1TestNg', '354'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/2Grid',
        component: ComponentCreator('/2Grid', '4c4'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/2Jmeter',
        component: ComponentCreator('/2Jmeter', '3e0'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/2Maven',
        component: ComponentCreator('/2Maven', '83c'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/API-Testing-Concepts/API Basics',
        component: ComponentCreator('/API-Testing-Concepts/API Basics', '459'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/API-Testing-Concepts/HTTP Basics',
        component: ComponentCreator('/API-Testing-Concepts/HTTP Basics', 'c44'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/API-Testing-Concepts/static/API',
        component: ComponentCreator('/API-Testing-Concepts/static/API', 'f66'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/API-Testing-Concepts/static/APITesting',
        component: ComponentCreator('/API-Testing-Concepts/static/APITesting', '718'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Appium',
        component: ComponentCreator('/Appium', '37a'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Cucumber/Architecture',
        component: ComponentCreator('/Cucumber/Architecture', '204'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Cucumber/Dependency-Injection',
        component: ComponentCreator('/Cucumber/Dependency-Injection', 'cee'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Cucumber/ExtentReports',
        component: ComponentCreator('/Cucumber/ExtentReports', 'a0b'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Cucumber/Introduction',
        component: ComponentCreator('/Cucumber/Introduction', 'ec4'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Cucumber/static/Cucumber',
        component: ComponentCreator('/Cucumber/static/Cucumber', '087'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Docker/',
        component: ComponentCreator('/Docker/', '32d'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Docker/Compose',
        component: ComponentCreator('/Docker/Compose', '935'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Docker/ContainerInteractions',
        component: ComponentCreator('/Docker/ContainerInteractions', '354'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Docker/Docker-Commands',
        component: ComponentCreator('/Docker/Docker-Commands', 'a21'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Docker/Docker-Introduction',
        component: ComponentCreator('/Docker/Docker-Introduction', '1fb'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Docker/DockerFiles/Docker Ignore file',
        component: ComponentCreator('/Docker/DockerFiles/Docker Ignore file', 'c92'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Docker/DockerFiles/DockerFile',
        component: ComponentCreator('/Docker/DockerFiles/DockerFile', '941'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Docker/DockerFiles/Nextjs Docker File',
        component: ComponentCreator('/Docker/DockerFiles/Nextjs Docker File', 'f27'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Docker/static/Docker',
        component: ComponentCreator('/Docker/static/Docker', 'f36'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/docs/ContactMe',
        component: ComponentCreator('/docs/ContactMe', '73a'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/DSA',
        component: ComponentCreator('/DSA', '656'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Jackson/Introduction',
        component: ComponentCreator('/Jackson/Introduction', 'e7a'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Java/Basics',
        component: ComponentCreator('/Java/Basics', '380'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Java/exception',
        component: ComponentCreator('/Java/exception', '449'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Java/InnerClass',
        component: ComponentCreator('/Java/InnerClass', 'fcc'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Java/IO',
        component: ComponentCreator('/Java/IO', '8b3'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Java/Multithreading',
        component: ComponentCreator('/Java/Multithreading', 'f39'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Java/static/Java',
        component: ComponentCreator('/Java/static/Java', 'b43'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Jira/Agile-Project',
        component: ComponentCreator('/Jira/Agile-Project', '7ac'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Jira/static/Agile',
        component: ComponentCreator('/Jira/static/Agile', '462'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Jira/WaterFall-Project',
        component: ComponentCreator('/Jira/WaterFall-Project', '4ed'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Kafka/Intro',
        component: ComponentCreator('/Kafka/Intro', 'b29'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Microservices/Introduction',
        component: ComponentCreator('/Microservices/Introduction', '10c'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Playwright/Introduction',
        component: ComponentCreator('/Playwright/Introduction', '804'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/PostMan/Introduction',
        component: ComponentCreator('/PostMan/Introduction', '271'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Practice-Sites/Practice',
        component: ComponentCreator('/Practice-Sites/Practice', '437'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Rest-Assured/Introduction',
        component: ComponentCreator('/Rest-Assured/Introduction', '3c0'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Robot-Framework',
        component: ComponentCreator('/Robot-Framework', 'f23'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Security-Testing/Browser-Cookies',
        component: ComponentCreator('/Security-Testing/Browser-Cookies', '84c'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Security-Testing/SQL-Basics',
        component: ComponentCreator('/Security-Testing/SQL-Basics', '9c1'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Security-Testing/SQL-Data-Manupulation',
        component: ComponentCreator('/Security-Testing/SQL-Data-Manupulation', 'b07'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Security-Testing/SQL-DataTypes',
        component: ComponentCreator('/Security-Testing/SQL-DataTypes', 'ae6'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Security-Testing/SQL-Injection',
        component: ComponentCreator('/Security-Testing/SQL-Injection', '22d'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Security-Testing/SQL-Operators',
        component: ComponentCreator('/Security-Testing/SQL-Operators', 'bd4'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Security-Testing/SQL-References',
        component: ComponentCreator('/Security-Testing/SQL-References', '6ec'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Security-Testing/XSS-Attack',
        component: ComponentCreator('/Security-Testing/XSS-Attack', '5a8'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Selenium/BrowserOptions',
        component: ComponentCreator('/Selenium/BrowserOptions', 'c59'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Selenium/Introduction',
        component: ComponentCreator('/Selenium/Introduction', '8be'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Selenium/Synchronisation',
        component: ComponentCreator('/Selenium/Synchronisation', 'da7'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Servlet/Introduction',
        component: ComponentCreator('/Servlet/Introduction', 'e59'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/SoapUI/Assertions',
        component: ComponentCreator('/SoapUI/Assertions', '552'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/SoapUI/Intro',
        component: ComponentCreator('/SoapUI/Intro', '643'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/SoapUI/project',
        component: ComponentCreator('/SoapUI/project', 'b1e'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/SoapUI/Properties',
        component: ComponentCreator('/SoapUI/Properties', 'f1a'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/SoapUI/Soap',
        component: ComponentCreator('/SoapUI/Soap', 'e4b'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/SoapUI/SoapAutomation',
        component: ComponentCreator('/SoapUI/SoapAutomation', 'e9e'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/SoapUI/static/SoapUI',
        component: ComponentCreator('/SoapUI/static/SoapUI', 'd9a'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/SoapUI/WSDL',
        component: ComponentCreator('/SoapUI/WSDL', '7ae'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/static/SeleniumExcalidraw',
        component: ComponentCreator('/static/SeleniumExcalidraw', '5cc'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Testing-Concepts/Adhoc-vs-Exploretory',
        component: ComponentCreator('/Testing-Concepts/Adhoc-vs-Exploretory', '18d'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Testing-Concepts/Blackbox-vs-Whitebox',
        component: ComponentCreator('/Testing-Concepts/Blackbox-vs-Whitebox', 'f15'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Testing-Concepts/Component-vs-Integration-Testing',
        component: ComponentCreator('/Testing-Concepts/Component-vs-Integration-Testing', 'c1b'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Testing-Concepts/Defect-LifeCycle',
        component: ComponentCreator('/Testing-Concepts/Defect-LifeCycle', '1f4'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Testing-Concepts/Functional-vs-NonFunctional',
        component: ComponentCreator('/Testing-Concepts/Functional-vs-NonFunctional', 'aec'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Testing-Concepts/Load-vs-Stress-Testing',
        component: ComponentCreator('/Testing-Concepts/Load-vs-Stress-Testing', '196'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Testing-Concepts/Priority-vs-severity',
        component: ComponentCreator('/Testing-Concepts/Priority-vs-severity', 'cca'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Testing-Concepts/Retesting-vs-Regression',
        component: ComponentCreator('/Testing-Concepts/Retesting-vs-Regression', 'be2'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Testing-Concepts/SDLC-vs-STLC',
        component: ComponentCreator('/Testing-Concepts/SDLC-vs-STLC', 'd88'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Testing-Concepts/Smoke-vs-Sanity',
        component: ComponentCreator('/Testing-Concepts/Smoke-vs-Sanity', '657'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Testing-Concepts/Test-Cases',
        component: ComponentCreator('/Testing-Concepts/Test-Cases', '97b'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Testing-Concepts/Test-Pyramid',
        component: ComponentCreator('/Testing-Concepts/Test-Pyramid', '992'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Testing-Concepts/TestCase',
        component: ComponentCreator('/Testing-Concepts/TestCase', '404'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Testing-Concepts/Testing-levels',
        component: ComponentCreator('/Testing-Concepts/Testing-levels', '1a4'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Testing-Concepts/TestPlan',
        component: ComponentCreator('/Testing-Concepts/TestPlan', '22f'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Testing-Concepts/Traceability-Matrix',
        component: ComponentCreator('/Testing-Concepts/Traceability-Matrix', '4fc'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Testing-Concepts/Verification-vs-Validation',
        component: ComponentCreator('/Testing-Concepts/Verification-vs-Validation', 'fe8'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Xray/',
        component: ComponentCreator('/Xray/', '255'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Xray/static/Xray',
        component: ComponentCreator('/Xray/static/Xray', '89c'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Xray/Terminology',
        component: ComponentCreator('/Xray/Terminology', 'db4'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Xray/TestCase',
        component: ComponentCreator('/Xray/TestCase', '437'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Xray/TestCoverage',
        component: ComponentCreator('/Xray/TestCoverage', '69f'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Xray/TestExecution',
        component: ComponentCreator('/Xray/TestExecution', 'bf3'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Xray/TestPlan',
        component: ComponentCreator('/Xray/TestPlan', 'b9a'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Xray/XrayReports',
        component: ComponentCreator('/Xray/XrayReports', 'deb'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Zephyr/',
        component: ComponentCreator('/Zephyr/', '83b'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Zephyr/Zephyr-Reports',
        component: ComponentCreator('/Zephyr/Zephyr-Reports', '632'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Zephyr/Zephyr-TestCase',
        component: ComponentCreator('/Zephyr/Zephyr-TestCase', 'ee0'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Zephyr/Zephyr-TestCycle',
        component: ComponentCreator('/Zephyr/Zephyr-TestCycle', 'b37'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      },
      {
        path: '/Zephyr/Zephyr-TestPlan',
        component: ComponentCreator('/Zephyr/Zephyr-TestPlan', '755'),
        exact: true,
        sidebar: "myAutogeneratedSidebar"
      }
    ]
  },
  {
    path: '*',
    component: ComponentCreator('*'),
  },
];
